server {
  listen 80;

  # PROD
  location / {
    proxy_pass http://frontend-prod:80;
  }

  # DEV
  location /dev/ {
    proxy_pass http://frontend-dev:80/;
  }

  # QA
  location /qa/ {
    proxy_pass http://frontend-qa:80/;
  }
}